### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by mengen100** [rsasaki0109/kalman_filter_localization#4]
How to build?

**Comment by rsasaki0109** [comment]
Have you ever used ros2 before?
I suggest you start with the tutorial
https://docs.ros.org/en/foxy/Tutorials.html

**Comment by mengen100** [comment]
Hi, thanks for your reply.
I finished installing the ROS environment. (both ROS1 and ROS2)
When I run `ros2 bag play -s rosbag_v2 test.bag`, what I am supposed to see? (I'm not seeing anything in Rviz)
Pleas bear with me cuz I'm new to ROS and Rviz.
Thanks

**Comment by mengen100** [comment]
I've figured out,  I needed to set gnss_pose in Rviz to the correct topic message.
Thanks.
