### ISSUE TITLE
error: ‘set_on_parameters_set_callback’ was not declared in this scope

### ISSUE THREAD

**Issue by JaySlamer** [rsasaki0109/kalman_filter_localization#7]
I did some googling and found out that this was caused by deprecated API. Do you mind migrating this project to newer version of ROS2, like galantic?
![Screenshot from 2022-03-08 15-06-40](https://user-images.githubusercontent.com/12229227/157184928-0400024c-394d-407a-9124-230fd1c8368a.png)

**Comment by rsasaki0109** [comment]
I do not currently intend to migrate this project to newer version of ROS2…
Pull requests are welcome.

**Comment by rsasaki0109** [comment]
Fix
https://github.com/rsasaki0109/kalman_filter_localization/pull/9
